### ISSUE TITLE
[Feature request] Ability to export .m3u playlist

### ISSUE THREAD

**Issue by nickdurante** [teticio/Deej-A.I.#4]
Hi teticio,

I find your work really impressive, congrats on this great work!
Using it I though that the ability to export the generated playlist to a .m3u file would be a great feature to make the program more portable.
Have you had any thoughts on that?

**Comment by teticio** [comment]
Thanks Nick

When you say you are using it, are you using the website that I trained on Spotify data, or are you applying it to your own music library? I'm assuming the latter, because I'm not sure a .m3u file would make much sense in the former case.

I ended up making a website to be able to stream my own music library using the playlist generation algorithm. If you are a bit adventurous, you can probably get this to work with your own data if you check out my deej-ai.online repo, where all the website code (minus some credentials and my mp3s) resides.

Thanks for the feedback!

**Comment by nickdurante** [comment]
Hi teticio,

Thanks, yes I've trained the model to use my library and I has been really useful for small house parties!
I'll have a look and see what I can do, thanks for getting back to me!

**Comment by teticio** [comment]
That is very satisfying for me to know, thank you. Being honest, I am not in a position to do much work on the repo these days, but you'd be more than welcome to fork it and we could see about merging your changes at a later date. I do recommend the website approach as I personally use it quite a lot.

Best, Rob

**Comment by nickdurante** [comment]
Thanks Rob, I'll see if I can manage it with time and skills I have available.
